### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by ul** [cgrand/xforms#1]
As far as I can see you do not use any Java-specific code, so giving `cljc` extension to the source file should be enough to add CLJS support. But, may be, also macro need to be wrapped using feature expression.

**Comment by cgrand** [comment]
I do use j.l.StringBuilder and it could be worked around using feature expression.
However at the moment I'm applying this lib to server stuff so it's not my top priority (but I'd consider a patch or PR).

**Comment by cgrand** [comment]
Done and released in 0.7.1
