### ISSUE TITLE
transjuxt with maps ostensibly only works on the first element of a collection

### ISSUE THREAD

**Issue by lvh** [cgrand/xforms#16]
```clojure
(def samples
  [{:a 1}
   {:b 2}
   {:c 3}
   {:a 1 :c 3}])

(eduction
 (xf/transjuxt [(map :a) (map :b) (map :c)])
 samples)
;; => ([1 nil nil])

(xf/transjuxt [(map :a) (map :b) (map :c)] samples)
;; => [1 nil nil]
```

Hopefully it's obvious what I was expecting :)

**Comment by cgrand** [comment]
well I'm not sure what you expect, my best guess is a vector of the map results (but it may also be a sequence of vectors). 
`(x/transjuxt [(comp (map :a) (x/into [])) (comp (map :b) (x/into [])) (comp (map :c) (x/into []))] samples)`

**Comment by cgrand** [comment]
Btw it's not that transjuxt only works on first item but only return first result (replace map by keep in your experiments).

**Comment by lvh** [comment]
Yep; that worked. Thanks!
