### ISSUE TITLE
Constantly function

### ISSUE THREAD

**Issue by ds923y** [cgrand/xforms#24]
I did not find a function constantly.  It would be convienient if one could be added.
```
(defn xform-constantly [value]
  (fn [xf]
    (fn ([] (xf))
      ([result] (xf result))
      ([result input] (xf result value)))))
```

**Comment by cgrand** [comment]
Well it's either `(map (constantly x))` or `(x/for [_ %] x)` (there are certainly more ways to write it), I don't think there's a strong case for making it a standalone function.

**Comment by ds923y** [comment]
Yes the case for it was only convenience.
