### ISSUE TITLE
How to match reductions behavior

### ISSUE THREAD

**Issue by SevereOverfl0w** [cgrand/xforms#30]
```
(into [] (x/reductions +) [10 10 10]) ;; => [0 10 20 30]
(reductions + [10 10 10]) ;; => [10 20 30]
```

Am I missing some way to do this?

**Comment by cgrand** [comment]
It’s the same difference than between transduce and reduce when knit is omitted.
Is it a blocker in a rewrite or an unexpected difference?

**Comment by SevereOverfl0w** [comment]
I can work around in my rewrite easily enough for my case without breaking my performance threshold, but caused me some bad data.

**Comment by cgrand** [comment]
Closing this issue as it's document in the docstring.
