### ISSUE TITLE
Infinity symbol is causing problems with clojurescript compiled output

### ISSUE THREAD

**Issue by bbss** [cgrand/xforms#31]
When compiling clojurescript for production use there is an issue that causes errors at runtime:

![image](https://user-images.githubusercontent.com/2758664/64503042-32f8b200-d304-11e9-9a0d-0d41ec4c2867.png)

It seems to be that the browser doesn't like the infinity symbol:
https://github.com/cgrand/xforms/blob/master/src/net/cgrand/xforms/rfs.cljc#L42

I'm not sure this issue belongs here as maybe the clojurescript compiler should catch this, but I'd like to report this here anyway.

**Comment by dcj** [comment]
@cgrand: thank you for the immediate fix!  very helpful!
