### ISSUE TITLE
JAR for version 0.19.1 contains broken code not in master

### ISSUE THREAD

**Issue by miikka** [cgrand/xforms#32]
I just tried upgrading to 0.19.1 and noticed that the [JAR on Clojars](https://clojars.org/repo/net/cgrand/xforms/0.19.1/xforms-0.19.1.jar) contains in `net/cgrand/xforms.cljc` a function called `reorder` that does not exist in the [current master](https://github.com/cgrand/xforms/blob/9808cc85558b8029cf9b418296ac075c2e1d06f6/src/net/cgrand/xforms.cljc). [Here's a full diff](https://gist.github.com/miikka/4b7e8cbe74901d048a7a47f15f4e6ca3) for the curious. This function causes warnings when compiling the file with ClojureScript, for example this one:

```
[Figwheel:WARNING] Compile Warning   target/public/cljs-out/dev/net/cgrand/xforms.cljc   line:814  column:18

  No such namespace: com.google.common.collect.MinMaxPriorityQueue, could not locate com/google/common/collect/MinMaxPriorityQueue.cljs, com/google/common/collect/MinMaxPriorityQueue.cljc, or JavaScript source providing "com.google.commo
on.collect.MinMaxPriorityQueue"

  809  
  810  (defn reorder [n kfn drop!]
  811    (let [cmp (fn [a b] (- (kfn a) (kfn b)))]
  812      (fn [rf]
  813        (let [q (->
  814                  (com.google.common.collect.MinMaxPriorityQueue/orderedBy cmp)
                        ^---
  815                  (.maximumSize (inc n)) ; transiently holds 1 more
  816                  .create)
  817              vprev (volatile! nil)]
  818          (fn
  819            ([] (rf))
```

I'd recommend a re-release with a clean checkout of master.

**Comment by cgrand** [comment]
Sorry for the inconvenience. `0.19.2` is out to fix this. Please reopen this issue if it's still bad.

**Comment by miikka** [comment]
It works now! Thanks!
