### ISSUE TITLE
`cata`?

### ISSUE THREAD

**Issue by eraserhd** [cgrand/xforms#4]
I'm teasing out transducers and processes for [Avi](https://github.com/maitria/avi).  I have a pretty general context for catamorphisms [here](https://github.com/maitria/avi/blob/master/src/avi/layout/panes.clj#L77).  I'm still reasoning through a few corner cases to make sure it's golden, but would you like it?  This project seems like a good place for it to go.

**Comment by eraserhd** [comment]
Also, maybe `annotate` - I've broken out stuff that could be contributed here.

https://github.com/maitria/avi/blob/master/src/avi/xforms.clj

**Comment by cgrand** [comment]
I haven't thought enough about transducing trees. Well core Clojure itself is half-equipped for trees:
- zippers are generic but feel imperative,
- tree-seq always need some filtering and does no rebuilding
- `clojure.walk` has no open definition of what is a node.
