### ISSUE TITLE
`into` always returns the value wrapped in a seq

### ISSUE THREAD

**Issue by johnmn3** [cgrand/xforms#43]
I'm playing around with xforms, trying to use them with [`injest`](https://github.com/johnmn3/injest).

Without transducers, we might want to do this:
```
(->> [:a :b :c]
     (into [:default :foo])
     (map name)
     reverse)
;=> ("c" "b" "a" "foo" "default")
```
With `injest`, one might want to try to do:
```
(x>> [:a :b :c]
     (x/into [:default :foo])
     (map name)
     reverse)
; Execution error (ClassCastException) at net.cgrand.xforms/reduce$fn$reify (xforms.cljc:151).
; class clojure.lang.PersistentVector cannot be cast to class clojure.lang.Named (clojure.lang.PersistentVector and clojure.lang.Named are in unnamed module of loader 'app')
```
Because `into` is returning the resulting vector wrapped in a sequence.

Even removing the `map` step:
```
(x>> [:a :b :c]
     (x/into [:default :foo])
     reverse)
;=> ([:default :foo :a :b :c])
```
Not reversed like we'd expect.

In other use cases, perhaps returning the `into`'d target value wrapped in a lazy seq is preferable. But for these kinds of ergonomics it causes friction.

I'm wondering if there's any workaround for this, to make them behave more like their core variants. Is the current behavior there to prevent the target type from being coerced into a seq while passing through transformations? Is it even possible to force outer types when trying to compose arbitrary transducers?

Thanks for this awesome library!

**Comment by imrekoszo** [comment]
Leaving injest out of your repro returns the expected result:

```clojure
(->> [:a :b :c]
     (x/into [:default :foo])
     (map name)
     reverse)
;=> ("c" "b" "a" "foo" "default")
```

So I suspect the issue is around how injest uses `x/into`. Do remember that `x/into` has an arity that returns a transducer.

**Comment by johnmn3** [comment]
Hmm, okay I'll look into it. Thanks for checking @imrekoszo !!
