### ISSUE TITLE
questionable line in `trial`

### ISSUE THREAD

**Issue by rebcabin** [cgrand/xforms#8]
I noticed the following line in the tests

        (trial xform n (repeatedly #(#?(:clj Object. :clj js/Object.))) coll))

and thought the second term might be a typo. Perhaps the line should be

        (trial xform n (repeatedly #(#?(:clj Object. :cljs js/Object.))) coll))

I'd have tried it but I don't yet know how to run ClojureScript.

**Comment by cgrand** [comment]
Thanks, good catch.
